language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION="7.4"
    - RACKET_VERSION="7.5"
    - RACKET_VERSION="7.6"
    - RACKET_VERSION="7.7"
    - RACKET_VERSION="7.8"
    - RACKET_VERSION="7.9"
    - RACKET_VERSION="HEAD"
matrix:
  allow_failures:
    - env: RACKET_VERSION="HEAD"

addons:
  apt:
    update: true
    packages:
      - nasm
      - graphviz

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git ../travis-racket
  - cat ../travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  # install Turnstile, use `master` branch
  # - git clone https://github.com/stchang/macrotypes.git
  # - raco pkg install --auto macrotypes/macrotypes-lib/
  # - raco pkg install --auto macrotypes/turnstile-lib/
  # - raco pkg install --auto macrotypes/rackunit-macrotypes-lib/
  - raco pkg install --skip-installed --batch --auto https://github.com/cpsc411/cpsc411-pub.git?path=cpsc411-lib#2020w2
  - git clone https://$GITHUB_TOKEN@github.com/cpsc411/compilers2.0.git
  - raco pkg install --skip-installed --batch --auto compilers2.0/cpsc411-priv/cpsc411-reference-tests compilers2.0/cpsc411-priv/cpsc411-reference-lib

install:
 - raco pkg install --skip-installed --batch --auto https://github.com/cpsc411/cpsc411-book.git#main

script:
# - raco test --package cpsc411-reference-lib
# - raco test --package cpsc411-reference-tests
 - raco test --package cpsc411-book
 - raco setup
